Repository ros-planning/moveit2_tutorials, pull requests merged in 2021-11, with the labels that each got.

#181 Add mergify for backporting PRs
  .github/mergify.yml
Labels: backport-foxy, backport-galactic

#187 Fix branch in link to panda_arm.xacro
  doc/moveit_cpp/src/moveit_cpp_tutorial.cpp
Labels: backport-galactic

#186 Misc fixes to tutorials
  .github/config.yml
  README.md
  _themes/sphinx_rtd_theme/moveit1_warning.html
  doc/move_group_interface/move_group_interface_tutorial.rst
  doc/moveit_cpp/moveitcpp_tutorial.rst
  doc/planning_scene_ros_api/planning_scene_ros_api_tutorial.rst
  doc/urdf_srdf/urdf_srdf_tutorial.rst
  index.rst
Labels: backport-galactic

#189 graph fix
  moveit2_tutorials.repos
Labels: foxy, backport-galactic

#198 Fix response future type
  doc/planning_scene_ros_api/src/planning_scene_ros_api_tutorial.cpp
Labels: backport-foxy, backport-galactic

#218 Remove build folder before htmlproofer and make sure html urls are swapped
  htmlproofer.sh
Labels: foxy

#217 Fix extra slashes in github urls
  conf.py
Labels: foxy
