Repository ros-planning/moveit2_tutorials, pull requests merged in 2022-06, with the labels that each got.

#395 Add humble API
  Makefile
Labels: backport-foxy, backport-galactic, backport-humble

#400 Add Humble logo to tutorials
  _static/images/humble-small.png
Labels: backport-foxy, backport-galactic, backport-humble

#411 Bulk rename ws_moveit2 --> ws_moveit
  doc/examples/mobile_base_arm/mobile_base_arm_tutorial.rst
  doc/how_to_contribute/how_to_contribute_to_site.rst
  doc/tutorials/getting_started/getting_started.rst
  doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.rst
  doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
  doc/tutorials/your_first_project/your_first_project.rst
Labels: backport-foxy, backport-galactic, backport-humble

#423 Doxygen guide
  doc/how_to_guides/how_to_guides.rst
  doc/how_to_guides/how_to_write_doxygen.rst
Labels: backport-galactic, backport-humble

#433 Remove everything from repos except MTC
  .github/upstream.repos
  moveit2_tutorials.repos
Labels: backport-humble

#435 Update pre-commit runner to 22.04
  .github/workflows/format.yml
Labels: backport-humble

#437 Add dependabot
  .github/dependabot.yml
Labels: enhancement
